[package]
name = "my-game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "*", features = "dynamic_linking" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
